In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('~/Downloads/ten_rows.csv')

In [ ]:
df.head(10)

,Unnamed: 0,V1,clairDStore[1],clairDStore[2],clairDStore[3],clairDStore[4],clairDStore[5],clairDStore[6],clairDStore[7],clairDStore[8],...,ySuperiorRunoff6PP[860],ySuperiorRunoff6PP[861],ySuperiorRunoff6PP[862],ySuperiorRunoff6PP[863],ySuperiorRunoff6PP[864],ySuperiorRunoff6PP[865],ySuperiorRunoff6PP[866],ySuperiorRunoff6PP[867],ySuperiorRunoff6PP[868],ySuperiorRunoff6Prec
0,1,1,52.521100,-117.812391,153.820642,192.670123,75.708439,85.616433,-46.456519,31.327061,...,32.245023,25.775798,25.127041,27.900196,34.794870,32.742192,22.317617,19.207048,91.577909,0.030420
1,2,2,57.636378,-109.955859,144.866899,188.516383,89.253593,81.868385,-42.000136,11.155656,...,26.678189,15.028864,35.669512,29.458592,40.748149,28.454770,36.019461,41.574380,90.577811,0.029491
2,3,3,50.991254,-114.403718,152.466605,177.609038,107.898578,86.409636,-62.950192,24.842613,...,32.051315,25.959445,35.506979,28.339035,38.174150,41.997672,27.843433,28.911514,95.143097,0.033455
3,4,4,57.090801,-107.294935,153.805138,194.763396,93.424987,80.752274,-67.218023,16.267842,...,26.829297,31.950965,38.608032,28.002121,47.818895,27.057541,23.758726,32.576500,96.056095,0.030906
4,5,5,58.803277,-104.045820,156.191444,167.160592,113.349792,59.133872,-53.132201,7.295535,...,26.699526,23.002911,38.841791,16.368845,39.468123,43.074098,31.550517,31.321688,98.964125,0.028537
5,6,6,44.459249,-102.529802,150.642160,196.461428,98.239705,55.926846,-46.671806,7.163103,...,30.135683,32.330484,30.114634,22.024459,43.040513,30.585890,28.673090,24.407185,84.227998,0.031234
6,7,7,71.280258,-114.938381,147.079446,180.334847,89.655325,62.719442,-58.551844,24.766992,...,36.755751,25.920147,26.908047,28.512117,41.551892,35.700074,18.999876,32.399945,96.009371,0.031279
7,8,8,66.555836,-124.711046,152.544180,185.499269,102.084595,63.042262,-45.765597,9.071796,...,18.606618,20.235932,36.822119,35.763130,47.556981,45.839248,19.628554,29.941990,84.506607,0.034409
8,9,9,68.128610,-140.567373,169.545958,190.596640,106.033141,44.684839,-48.634580,21.620496,...,33.121867,14.505957,28.475943,36.532713,41.160625,20.081126,26.626224,24.847505,79.327824,0.032490
9,10,10,73.862953,-115.256130,163.801151,193.297633,96.444969,48.367564,-63.482255,14.627549,...,30.978187,14.693665,34.284286,35.219946,51.138325,26.612704,19.116689,33.903744,94.431755,0.030613

In [ ]:
tdf = df.transpose()

In [ ]:
tdf.head(10)

,0,1,2,3,4,5,6,7,8,9,10
clairDStore[1],52.521100,57.636378,50.991254,57.090801,58.803277,44.459249,71.280258,66.555836,68.128610,73.862953,79.452989
clairDStore[2],-117.812391,-109.955859,-114.403718,-107.294935,-104.045820,-102.529802,-114.938381,-124.711046,-140.567373,-115.256130,-134.966456
clairDStore[3],153.820642,144.866899,152.466605,153.805138,156.191444,150.642160,147.079446,152.544180,169.545958,163.801151,183.792227
clairDStore[4],192.670123,188.516383,177.609038,194.763396,167.160592,196.461428,180.334847,185.499269,190.596640,193.297633,166.463215
clairDStore[5],75.708439,89.253593,107.898578,93.424987,113.349792,98.239705,89.655325,102.084595,106.033141,96.444969,100.808951
clairDStore[6],85.616433,81.868385,86.409636,80.752274,59.133872,55.926846,62.719442,63.042262,44.684839,48.367564,64.883720
clairDStore[7],-46.456519,-42.000136,-62.950192,-67.218023,-53.132201,-46.671806,-58.551844,-45.765597,-48.634580,-63.482255,-74.703706
clairDStore[8],31.327061,11.155656,24.842613,16.267842,7.295535,7.163103,24.766992,9.071796,21.620496,14.627549,12.264577
clairDStore[9],-65.340338,-43.835879,-50.146610,-55.028813,-40.085165,-39.612626,-43.842152,-66.271849,-67.575344,-53.980892,-60.279378
clairDStore[10],-107.139438,-128.637256,-134.328071,-113.502871,-131.453717,-142.634413,-132.884824,-134.539700,-143.904198,-139.685365,-128.007154

In [ ]:
tdf = tdf.drop(index='Unnamed: 0')

In [ ]:
tdf.index

Index(['clairDStore[1]', 'clairDStore[2]', 'clairDStore[3]', 'clairDStore[4]',
       'clairDStore[5]', 'clairDStore[6]', 'clairDStore[7]', 'clairDStore[8]',
       'clairDStore[9]', 'clairDStore[10]',
       ...
       'ySuperiorRunoff6PP[860]', 'ySuperiorRunoff6PP[861]',
       'ySuperiorRunoff6PP[862]', 'ySuperiorRunoff6PP[863]',
       'ySuperiorRunoff6PP[864]', 'ySuperiorRunoff6PP[865]',
       'ySuperiorRunoff6PP[866]', 'ySuperiorRunoff6PP[867]',
       'ySuperiorRunoff6PP[868]', 'ySuperiorRunoff6Prec'],
      dtype='object', length=120386)

In [ ]:
type(tdf.index)

pandas.core.indexes.base.Index

In [ ]:
# Create a new column with index values
tdf['index_column'] = tdf.index

#using reset_index() to set index into column
tdf2=tdf.reset_index()

In [ ]:
tdf2

,index,0,1,2,3,4,5,6,7,8,9,10,index_column
0,clairDStore[1],52.521100,57.636378,50.991254,57.090801,58.803277,44.459249,71.280258,66.555836,68.128610,73.862953,79.452989,clairDStore[1]
1,clairDStore[2],-117.812391,-109.955859,-114.403718,-107.294935,-104.045820,-102.529802,-114.938381,-124.711046,-140.567373,-115.256130,-134.966456,clairDStore[2]
2,clairDStore[3],153.820642,144.866899,152.466605,153.805138,156.191444,150.642160,147.079446,152.544180,169.545958,163.801151,183.792227,clairDStore[3]
3,clairDStore[4],192.670123,188.516383,177.609038,194.763396,167.160592,196.461428,180.334847,185.499269,190.596640,193.297633,166.463215,clairDStore[4]
4,clairDStore[5],75.708439,89.253593,107.898578,93.424987,113.349792,98.239705,89.655325,102.084595,106.033141,96.444969,100.808951,clairDStore[5]
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120381,ySuperiorRunoff6PP[865],32.742192,28.454770,41.997672,27.057541,43.074098,30.585890,35.700074,45.839248,20.081126,26.612704,31.273263,ySuperiorRunoff6PP[865]
120382,ySuperiorRunoff6PP[866],22.317617,36.019461,27.843433,23.758726,31.550517,28.673090,18.999876,19.628554,26.626224,19.116689,27.086442,ySuperiorRunoff6PP[866]
120383,ySuperiorRunoff6PP[867],19.207048,41.574380,28.911514,32.576500,31.321688,24.407185,32.399945,29.941990,24.847505,33.903744,34.509956,ySuperiorRunoff6PP[867]
120384,ySuperiorRunoff6PP[868],91.577909,90.577811,95.143097,96.056095,98.964125,84.227998,96.009371,84.506607,79.327824,94.431755,85.573981,ySuperiorRunoff6PP[868]
120385,ySuperiorRunoff6Prec,0.030420,0.029491,0.033455,0.030906,0.028537,0.031234,0.031279,0.034409,0.032490,0.030613,0.031638,ySuperiorRunoff6Prec

In [ ]:
df = tdf2

In [ ]:
df = df[df["index"].str.contains("DStore")==False]

In [ ]:
df

,index,0,1,2,3,4,5,6,7,8,9,10,index_column
868,clairNBS[1],491.219691,430.615518,508.018332,439.589262,561.217738,464.150444,434.466020,483.840624,457.183853,394.134771,498.004393,clairNBS[1]
869,clairNBS[2],368.396291,376.561019,295.999410,211.960230,196.587261,210.782201,126.612763,173.173128,210.114203,289.008191,259.747608,clairNBS[2]
870,clairNBS[3],361.384463,474.833447,420.737391,404.511243,381.395621,409.604239,330.293851,393.803792,436.225535,487.990364,493.390171,clairNBS[3]
871,clairNBS[4],407.839169,379.534188,405.061524,424.830297,528.103088,564.526456,590.028347,550.095092,627.890478,566.232977,523.695564,clairNBS[4]
872,clairNBS[5],230.301774,182.307770,160.196599,190.274350,167.082427,164.085907,158.824897,228.192675,175.124604,135.342040,114.681931,clairNBS[5]
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120381,ySuperiorRunoff6PP[865],32.742192,28.454770,41.997672,27.057541,43.074098,30.585890,35.700074,45.839248,20.081126,26.612704,31.273263,ySuperiorRunoff6PP[865]
120382,ySuperiorRunoff6PP[866],22.317617,36.019461,27.843433,23.758726,31.550517,28.673090,18.999876,19.628554,26.626224,19.116689,27.086442,ySuperiorRunoff6PP[866]
120383,ySuperiorRunoff6PP[867],19.207048,41.574380,28.911514,32.576500,31.321688,24.407185,32.399945,29.941990,24.847505,33.903744,34.509956,ySuperiorRunoff6PP[867]
120384,ySuperiorRunoff6PP[868],91.577909,90.577811,95.143097,96.056095,98.964125,84.227998,96.009371,84.506607,79.327824,94.431755,85.573981,ySuperiorRunoff6PP[868]
120385,ySuperiorRunoff6Prec,0.030420,0.029491,0.033455,0.030906,0.028537,0.031234,0.031279,0.034409,0.032490,0.030613,0.031638,ySuperiorRunoff6Prec

In [ ]:
superiorPrecip = df[df["index"].str.contains("superiorPrecip")==True]

In [ ]:
superiorPrecip

,index,0,1,2,3,4,5,6,7,8,9,10,index_column
41558,superiorPrecip[1],93.501024,85.261796,83.038862,88.010966,79.703767,77.653931,79.794386,88.175817,88.530228,92.775109,85.689880,superiorPrecip[1]
41559,superiorPrecip[2],37.183604,37.700553,40.217322,38.693038,37.338572,34.180673,33.420857,37.988889,30.728594,28.896143,36.560157,superiorPrecip[2]
41560,superiorPrecip[3],59.081297,38.485733,58.348806,50.210284,48.147285,56.173625,51.899811,52.675603,55.180767,53.820089,43.918010,superiorPrecip[3]
41561,superiorPrecip[4],86.287725,70.508125,80.718903,73.625040,75.998241,73.898214,74.278147,72.963291,64.137892,70.762943,75.282947,superiorPrecip[4]
41562,superiorPrecip[5],100.666931,99.672702,96.905667,107.355880,110.784213,105.305023,98.606699,112.023825,92.681319,119.124119,110.629290,superiorPrecip[5]
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42421,superiorPrecip[864],58.928265,83.199542,81.596000,85.566538,76.125041,85.321047,74.918124,72.352237,84.519719,82.542314,71.001429,superiorPrecip[864]
42422,superiorPrecip[865],67.133831,62.835312,55.558559,51.289074,46.056754,55.506286,62.718288,68.131698,46.705737,61.911186,61.305698,superiorPrecip[865]
42423,superiorPrecip[866],48.184346,48.188907,55.327119,54.033775,41.135934,46.152943,48.895490,58.655170,53.627778,52.698878,46.574296,superiorPrecip[866]
42424,superiorPrecip[867],52.237437,49.964399,53.390431,43.985384,53.199893,56.805253,43.157934,62.141953,64.754631,58.733562,68.013421,superiorPrecip[867]
42425,superiorPrecip[868],107.858829,117.907490,111.555871,97.292625,109.331621,110.781390,110.944349,120.075746,96.131486,106.050987,112.862154,superiorPrecip[868]

In [ ]:
t = superiorPrecip.loc[:, 1]
t = pd.DataFrame(data=t)
t = t.rename(columns={1: "Median"})
t = t[:840]
t

           Median
41558   85.261796
41559   37.700553
41560   38.485733
41561   70.508125
41562   99.672702
...           ...
42393   78.284321
42394  113.392847
42395   89.565907
42396   60.049721
42397   70.335639

[840 rows x 1 columns]

In [ ]:
names = ['superiorPrecip', 'superiorEvap','superiorRunoff','miHuronPrecip','miHuronEvap','miHuronRunoff',
        'eriePrecip','erieEvap','erieRunoff']

In [ ]:
for name in names:
    for i in range(0,10):
        t = superiorPrecip.loc[:, i]
        t = pd.DataFrame(data=t)
        t = t.rename(columns={i:"Median"})
        t = t[:840]
        t.to_csv(name + '_' + str(i) + '.csv', index=False)